version: '3.8'

services:
  app:
    build:
      context: ./apps/server
      target: builder
    volumes:
      - ./apps/server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/routine_todo
      - NODE_ENV=development
    depends_on:
      - db
    command: pnpm dev

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routine_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  server_node_modules: 